# Generated by Django 6.0.5 on 2026-05-18 01:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial_notification_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventJourney",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("event_id", models.UUIDField(unique=True)),
                ("event_start", models.DateTimeField()),
                ("event_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notifications_event_journey",
            },
        ),
        migrations.CreateModel(
            name="JourneyStage",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("event_id", models.UUIDField()),
                ("stage_type", models.CharField(max_length=50)),
                ("trigger_at", models.DateTimeField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("fired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="notifications.eventjourney",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_journey_stage",
            },
        ),
    ]
